#include "main.h"
#include <stdlib.h>

/**
 * free_gind - Frees memory of grid generated by the **alloc_grid function
 *
 * @grid: pointer to grid
 *
 * @height: height of grid
 *
 * Return: void
 */

void free_grid(int **grid, int height)
{
	int i;

	if (grid != NULL)
	{
		for (i = 0; i < height; i++)
		{
			free(grid[i]);
		}

		free(grid);
	}
}
